# Generated by Django 4.2.16 on 2024-10-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_alter_review_rating"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("book", "reviewer"), name="unique_book_reviewer"
            ),
        ),
    ]
